services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4        
    container_name: lavalink
    env_file: .env                                   
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
    ports:
      - "2333:2333"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./logs:/opt/Lavalink/logs
    restart: unless-stopped
    networks:
      - bot-network

  bot:
    build: ./bot
    container_name: piumbot
    env_file: .env
    environment:
      - LAVALINK_HOST=lavalink
      - LAVALINK_PORT=2333
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD}
    depends_on:
      - lavalink
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
